package ie.spring.heroes;
import ie.spring.heroes.daos.HeroRepository;
import ie.spring.heroes.daos.entities.Hero;
import ie.spring.heroes.daos.entities.Name;
import ie.spring.heroes.service.AlreadyExists;
import ie.spring.heroes.service.HeroNotFoundException;
import ie.spring.heroes.service.HeroService;
import ie.spring.heroes.service.HeroServiceImpl;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

// Starter code generated by ChatGPT on September 30th 2025
// This tests the service layer as unit tests, mocking the behaviour of
// the repository layer.

class HeroServiceImplUnitTest {

    HeroRepository heroRepository = mock(HeroRepository.class);
    HeroService heroService = new HeroServiceImpl(heroRepository);


    @Test
    void save_shouldSaveHero_whenAliasDoesNotExist() {
        Hero hero = new Hero();
        hero.setAlias("Superman");

        when(heroRepository.existsByAlias("Superman")).thenReturn(false);
        when(heroRepository.save(hero)).thenReturn(hero);

        Hero result = heroService.save(hero);

        assertEquals(hero, result);
        verify(heroRepository).save(hero);
    }

    @Test
    void save_shouldThrowAlreadyExists_whenAliasExists() {
        Hero hero = new Hero();
        hero.setAlias("Batman");

        when(heroRepository.existsByAlias("Batman")).thenReturn(true);

        assertThrows(AlreadyExists.class, () -> heroService.save(hero));
        verify(heroRepository, never()).save(any());
    }

    @Test
    void changeUniverse_shouldCallRepository_whenHeroExists() {
        when(heroRepository.changeUniverse(1, "Marvel")).thenReturn(1);

        assertDoesNotThrow(() -> heroService.changeUniverse(1, "Marvel"));
        verify(heroRepository).changeUniverse(1, "Marvel");
    }

    @Test
    void changeUniverse_shouldThrowException_whenHeroNotFound() {
        when(heroRepository.changeUniverse(1, "Marvel")).thenReturn(0);

        assertThrows(HeroNotFoundException.class, () -> heroService.changeUniverse(1, "Marvel"));
    }

    @Test
    void count_shouldReturnTotalHeroCount() {
        when(heroRepository.count()).thenReturn(5);

        int count = heroService.count();

        assertEquals(5, count);
        verify(heroRepository).count();
    }

    @Test
    void countByUniverse_shouldReturnCorrectCount() {
        when(heroRepository.countByUniverse("DC")).thenReturn(3);

        int count = heroService.countByUniverse("DC");

        assertEquals(3, count);
        verify(heroRepository).countByUniverse("DC");
    }

    @Test
    void findAll_shouldReturnAllHeroes() {
        List<Hero> heroes = List.of(new Hero(), new Hero());

        when(heroRepository.findAll()).thenReturn(heroes);

        List<Hero> result = heroService.findAll();

        assertEquals(2, result.size());
        verify(heroRepository).findAll();
    }

    @Test
    void findAllNames_shouldReturnAllHeroNames() {
        List<Name> names = List.of(new Name("Clark", "Kent"), new Name("Bruce", "Wayne"));

        when(heroRepository.findAllNames()).thenReturn(names);

        List<Name> result = heroService.findAllNames();

        assertEquals(2, result.size());
        verify(heroRepository).findAllNames();
    }

    @Test
    void findById_shouldReturnHero_whenFound() {
        Hero hero = new Hero();
        hero.setHeroId(1);

        when(heroRepository.findById(1)).thenReturn(Optional.of(hero));

        Hero result = heroService.findById(1);

        assertEquals(hero, result);
        verify(heroRepository).findById(1);
    }

    @Test
    void findById_shouldThrowException_whenNotFound() {
        when(heroRepository.findById(1)).thenReturn(Optional.empty());

        assertThrows(HeroNotFoundException.class, () -> heroService.findById(1));
    }

    @Test
    void deleteById_shouldDeleteHero_whenExists() {
        when(heroRepository.deleteById(1)).thenReturn(1);

        assertDoesNotThrow(() -> heroService.deleteById(1));
        verify(heroRepository).deleteById(1); // verify that heroRepository's deleteById() is called exactly once
    }

    @Test
    void deleteById_shouldThrowException_whenHeroNotFound() {
        when(heroRepository.deleteById(1)).thenReturn(0);

        assertThrows(HeroNotFoundException.class, () -> heroService.deleteById(1));
    }
}

